admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin
blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog
app:
    resource: '@AppBundle/Controller/'
    type: annotation
